apiVersion: v1
kind: ConfigMap
metadata:
  name: immufluent-config
data:
  IF_IMMUDB_HOSTNAME: hostname_here
  IF_IMMUDB_PATTERN: "log_%Y_%m"
  IF_BUFFER_SIZE: "100"
  IF_BUFFER_DELAY: "500"
---
apiVersion: v1
kind: Secret
metadata:
  name: immufluent-credentials
stringData:
  IF_IMMUDB_USERNAME: immudb
  IF_IMMUDB_PASSWORD: immudb
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app.kubernetes.io/component: immufluent
  name: immufluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: immufluent
  template:
    metadata:
      labels:
        app.kubernetes.io/component: immufluent
    spec:
      containers:
      - name: immufluent
        envFrom:
        - configMapRef: 
            name: immufluent-config
        - secretRef: 
            name: immufluent-credentials
        image: slazzaris/immufluent:v1.0.0
        livenessProbe:
          httpGet:
            path: /ping
            port: 8090
        ports:
        - containerPort: 8090
          protocol: TCP
          name: log
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app.kubernetes.io/component: immufluent
  name: immufluent
spec:
  ports:
  - name: log
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app.kubernetes.io/component: immufluent
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: immufluent
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: immufluent
  podMetricsEndpoints:
  - port: log
    path: /metrics

